global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9093
    api_version: v2

rule_files:
- "*rules.y*ml"
- "*_alerts.y*ml"

scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9090
- job_name: alertmanager
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9093
- job_name: node_exporter
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9100
# Unreachable target intentionally configured to demonstrate the up metric and friends.
- job_name: unreachable
  static_configs:
  - targets:
    - 127.0.0.1
