global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s

scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9090
- job_name: blackbox_exporter
  metrics_path: /probe
  scheme: http
  params:
    module: [http_2xx]
  static_configs:
  - targets:
    - https://www.devoxx.fr
    - https://www.google.com
    - http://example.com
    - http://127.0.0.1:9999
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9115
    # deal with SSH targets
    - source_labels: [__param_target]
      target_label: __param_module
      regex: ssh://.+
      replacement: ssh_banner
    - source_labels: [__param_target]
      target_label: __param_target
      regex: ssh://([^:]+):([^$]+)
      replacement: ${1}:${2}
